name: Docker Build and Publish

on:
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pandiff:latest,${{ vars.DOCKERHUB_USERNAME }}/pandiff:${{ github.event.release.tag_name }}

